/**
 * WC2030 Scout — prediction market pricing engine.
 *
 * IMPORTANT — DEMO / IN-MEMORY STATE, NOT PERSISTENT:
 * All order-book state (volume, holdings) lives in a module-level Map in this
 * server process. On Vercel this is a serverless function — every cold start
 * (new deploy, scale-to-zero, new region instance) wipes this Map back to its
 * deterministic seed. There is no database. Nothing here is real money — the
 * "price" is a demo PIEUSD-denominated number derived from prediction
 * probabilities plus synthetic order flow. See README "Prediction Market"
 * section and the /market page footnote for the same disclaimer.
 *
 * Pricing model:
 *   base   = prob / 100                              (0..1, from Gonka mean or heuristic fallback)
 *   price  = clamp(0.01, 0.99, base * (1 + 0.05 * tanh(netVolume / 20)))
 * netVolume is buy qty minus sell qty accumulated in-memory for that player,
 * seeded with a small deterministic pseudo-random "starting flow" per player
 * slug so the board doesn't look perfectly flat/identical on every cold start.
 */
import fs from "node:fs";
import path from "node:path";
import { loadSquads, loadPredictions } from "./data";
import { slugify } from "./slug";
import type { Player, PlayerPrediction } from "./types";
import type { MarketBaseFile } from "../scripts/reprice";

export type MarketSource = "dual-model" | "baseline";

export interface MarketEntry {
  slug: string;
  team: string; // team code
  name: string;
  position: Player["position"];
  prob: number; // 0-100 display probability backing the base price
  source: MarketSource;
}

interface Holding {
  /** net buy(+)/sell(-) quantity accumulated since process start (seed + trades). */
  volume: number;
  /** cumulative absolute traded quantity — used for "most traded" board. */
  turnover: number;
  seedPrice: number; // price at seed time, for a crude 24h-ish delta
  lastPrice: number;
  updatedAt: string;
}

const book = new Map<string, Holding>();
let entriesCache: MarketEntry[] | null = null;

/** Same longevity/tier heuristics style as lib/heuristics.ts, adapted for a
 *  standalone 0-100 "market baseline" probability for players with no model
 *  prediction yet (precompute.ts hasn't reached them). Cheap, deterministic. */
const LEAGUE_TIER: Record<string, number> = {
  "Premier League": 10,
  "La Liga": 9.5,
  "Bundesliga": 9,
  "Serie A": 8.5,
  "Ligue 1": 8,
  "Saudi Pro League": 6,
  MLS: 6,
  "Liga Portugal": 7,
  Eredivisie: 7,
  "Süper Lig": 6,
  "J1 League": 5.5,
  "Liga Profesional Argentina": 5.5,
  "Brasileirão": 6,
  "Botola Pro": 4.5,
};

const POSITION_LONGEVITY: Record<Player["position"], number> = {
  GK: 38,
  DF: 35,
  MF: 34,
  FW: 33,
};

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

function baselineProbability(p: Player): number {
  const age2030 = 2030 - p.birthYear;
  const longevity = POSITION_LONGEVITY[p.position];
  const ageGap = longevity - age2030;
  const ageScore = clamp(50 + ageGap * 9, 3, 100);
  const leagueScore = clamp((LEAGUE_TIER[p.league] ?? 5) * 10, 5, 100);
  const capsScore = clamp(Math.sqrt(p.caps) * 14, 3, 100);
  // No model call here — blend the same signals precompute.ts's prompt cares
  // about (age longevity, league level, caps depth) into one 0-100 number.
  return Math.round(ageScore * 0.55 + leagueScore * 0.25 + capsScore * 0.2);
}

/** Tiny deterministic PRNG (mulberry32) seeded from a string, so repeated
 *  cold starts produce a *consistent-ish* (not random every request) demo
 *  order-flow seed per player slug. */
function seededRandom(seed: string): () => number {
  let h = 1779033703 ^ seed.length;
  for (let i = 0; i < seed.length; i++) {
    h = Math.imul(h ^ seed.charCodeAt(i), 3432918353);
    h = (h << 13) | (h >>> 19);
  }
  return function () {
    h = Math.imul(h ^ (h >>> 16), 2246822519);
    h = Math.imul(h ^ (h >>> 13), 3266489917);
    h ^= h >>> 16;
    return (h >>> 0) / 4294967296;
  };
}

function priceForBase(base: number, netVolume: number): number {
  const adjusted = base * (1 + 0.05 * Math.tanh(netVolume / 20));
  return clamp(Number(adjusted.toFixed(4)), 0.01, 0.99);
}

/** data/market-base.json, produced by scripts/reprice.ts (decoupled from this
 *  server process — regenerated by the weekly cron). When present it's the
 *  preferred source of {prob, source} per player; falls back to the in-file
 *  logic below (predictions.json + baselineProbability) when it hasn't been
 *  generated yet, e.g. fresh local dev checkout. */
let marketBaseCache: MarketBaseFile | null | undefined;
function loadMarketBase(): MarketBaseFile | null {
  if (marketBaseCache !== undefined) return marketBaseCache;
  try {
    const raw = fs.readFileSync(path.join(process.cwd(), "data", "market-base.json"), "utf-8");
    marketBaseCache = JSON.parse(raw) as MarketBaseFile;
  } catch {
    marketBaseCache = null;
  }
  return marketBaseCache;
}

function buildEntries(): MarketEntry[] {
  const { teams } = loadSquads();
  const marketBase = loadMarketBase();
  const predictions = loadPredictions();
  const byKey = new Map<string, PlayerPrediction>();
  for (const pr of predictions.players) {
    byKey.set(`${pr.team.toUpperCase()}::${pr.name}`, pr);
  }
  const entries: MarketEntry[] = [];
  for (const team of teams) {
    for (const player of team.players) {
      const slug = slugify(player.name);
      const baseEntry = marketBase?.entries[`${team.code.toUpperCase()}::${slug}`];
      let prob: number;
      let source: MarketSource;
      if (baseEntry) {
        prob = baseEntry.prob;
        source = baseEntry.source === "model" ? "dual-model" : "baseline";
      } else {
        const pred = byKey.get(`${team.code.toUpperCase()}::${player.name}`);
        prob = pred ? pred.mean : baselineProbability(player);
        source = pred ? "dual-model" : "baseline";
      }
      entries.push({
        slug,
        team: team.code,
        name: player.name,
        position: player.position,
        prob,
        source,
      });
    }
  }
  return entries;
}

function key(team: string, slug: string): string {
  return `${team.toUpperCase()}::${slug}`;
}

function getEntries(): MarketEntry[] {
  // Cached for the lifetime of the process — squads/predictions files don't
  // change mid-request in this demo (they're regenerated by the weekly
  // workflow, which triggers a fresh deploy / cold start anyway).
  if (!entriesCache) entriesCache = buildEntries();
  return entriesCache;
}

function findEntry(slug: string, teamHint?: string): MarketEntry | undefined {
  const entries = getEntries();
  if (teamHint) {
    const hit = entries.find((e) => e.slug === slug && e.team.toUpperCase() === teamHint.toUpperCase());
    if (hit) return hit;
  }
  return entries.find((e) => e.slug === slug);
}

/** Lazily seeds (once) and returns the in-memory holding for a player. */
function getHolding(entry: MarketEntry): Holding {
  const k = key(entry.team, entry.slug);
  let h = book.get(k);
  if (!h) {
    const rand = seededRandom(k);
    // Deterministic-ish seed flow: -10..+10 net volume, so the board has
    // some spread of movers/losers right after a cold start.
    const seedVolume = Math.round((rand() - 0.5) * 20);
    const base = entry.prob / 100;
    const seedPrice = priceForBase(base, seedVolume);
    h = {
      volume: seedVolume,
      turnover: Math.abs(seedVolume),
      seedPrice,
      lastPrice: seedPrice,
      updatedAt: new Date().toISOString(),
    };
    book.set(k, h);
  }
  return h;
}

export interface Quote {
  slug: string;
  team: string;
  name: string;
  price: number;
  base: number;
  prob: number;
  source: MarketSource;
  volume: number;
  turnover: number;
  delta: number; // lastPrice - seedPrice, crude "24h-ish" move for the demo
  updatedAt: string;
}

export function getQuote(slug: string, teamHint?: string): Quote | null {
  const entry = findEntry(slug, teamHint);
  if (!entry) return null;
  const holding = getHolding(entry);
  const base = entry.prob / 100;
  const price = priceForBase(base, holding.volume);
  holding.lastPrice = price;
  return {
    slug: entry.slug,
    team: entry.team,
    name: entry.name,
    price,
    base: Number(base.toFixed(4)),
    prob: entry.prob,
    source: entry.source,
    volume: holding.volume,
    turnover: holding.turnover,
    delta: Number((price - holding.seedPrice).toFixed(4)),
    updatedAt: holding.updatedAt,
  };
}

export interface BoardRow extends Quote {}

export interface Board {
  topMovers: BoardRow[]; // largest |delta|
  mostTraded: BoardRow[]; // highest turnover
  highestPriced: BoardRow[];
  lowestPriced: BoardRow[];
  generatedAt: string;
  count: number;
}

export function getBoard(limit = 8): Board {
  const entries = getEntries();
  const rows = entries.map((e) => getQuote(e.slug, e.team)!).filter(Boolean);

  const topMovers = [...rows].sort((a, b) => Math.abs(b.delta) - Math.abs(a.delta)).slice(0, limit);
  const mostTraded = [...rows].sort((a, b) => b.turnover - a.turnover).slice(0, limit);
  const highestPriced = [...rows].sort((a, b) => b.price - a.price).slice(0, limit);
  const lowestPriced = [...rows].sort((a, b) => a.price - b.price).slice(0, limit);

  return {
    topMovers,
    mostTraded,
    highestPriced,
    lowestPriced,
    generatedAt: new Date().toISOString(),
    count: rows.length,
  };
}

/** Full board rows (all players), used by the /market table and trade-agent.mjs
 *  divergence scan — separate from the top-N summary lists in getBoard(). */
export function getAllQuotes(): BoardRow[] {
  return getEntries().map((e) => getQuote(e.slug, e.team)!);
}

export interface TradeFill {
  slug: string;
  team: string;
  side: "buy" | "sell";
  qty: number;
  fillPrice: number;
  newPrice: number;
  volume: number;
  updatedAt: string;
}

export function applyTrade(slug: string, side: "buy" | "sell", qty: number, teamHint?: string): TradeFill | null {
  const entry = findEntry(slug, teamHint);
  if (!entry) return null;
  if (!Number.isFinite(qty) || qty <= 0) throw new Error("qty must be a positive number");

  const holding = getHolding(entry);
  const base = entry.prob / 100;
  const fillPrice = priceForBase(base, holding.volume);

  const delta = side === "buy" ? qty : -qty;
  holding.volume += delta;
  holding.turnover += Math.abs(qty);
  holding.updatedAt = new Date().toISOString();

  const newPrice = priceForBase(base, holding.volume);
  holding.lastPrice = newPrice;

  return {
    slug: entry.slug,
    team: entry.team,
    side,
    qty,
    fillPrice,
    newPrice,
    volume: holding.volume,
    updatedAt: holding.updatedAt,
  };
}
