/**
 * reprice.ts — precompute per-player market base prices, decoupled from the
 * live server process.
 *
 * Reads data/predictions.json tolerantly (partial/missing entries are fine —
 * treated as "no prediction available" and heuristically priced instead), and
 * writes data/market-base.json: slug -> { base (0-1), prob (0-100), source }.
 *
 * lib/market.ts prefers this file when present (so pricing is stable across
 * cold starts / can be regenerated by the weekly cron without a server
 * restart), falling back to its own in-process heuristic when the file is
 * missing (e.g. local dev before this script has ever run).
 *
 * Usage: npx tsx scripts/reprice.ts
 */
import fs from "node:fs";
import path from "node:path";
import type { PredictionsData, SquadsData, Player } from "../lib/types";
import { slugify } from "../lib/slug";

const DATA_DIR = path.join(process.cwd(), "data");
const SQUADS_PATH = path.join(DATA_DIR, "squads.json");
const PREDICTIONS_PATH = path.join(DATA_DIR, "predictions.json");
const OUT_PATH = path.join(DATA_DIR, "market-base.json");

// Mirrors lib/heuristics.ts's tier tables — kept in sync deliberately (this
// script must stay usable standalone via tsx, without importing the Next.js
// app's runtime).
const LEAGUE_TIER: Record<string, number> = {
  "Premier League": 10,
  "La Liga": 9.5,
  "Bundesliga": 9,
  "Serie A": 8.5,
  "Ligue 1": 8,
  "Saudi Pro League": 6,
  MLS: 6,
  "Liga Portugal": 7,
  Eredivisie: 7,
  "Süper Lig": 6,
  "J1 League": 5.5,
  "Liga Profesional Argentina": 5.5,
  "Brasileirão": 6,
  "Botola Pro": 4.5,
};

const POSITION_LONGEVITY: Record<Player["position"], number> = {
  GK: 38,
  DF: 35,
  MF: 34,
  FW: 33,
};

function clamp(v: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, v));
}

function baselineProbability(p: Player): number {
  const age2030 = 2030 - p.birthYear;
  const longevity = POSITION_LONGEVITY[p.position];
  const ageGap = longevity - age2030;
  const ageScore = clamp(50 + ageGap * 9, 3, 100);
  const leagueScore = clamp((LEAGUE_TIER[p.league] ?? 5) * 10, 5, 100);
  const capsScore = clamp(Math.sqrt(p.caps) * 14, 3, 100);
  return Math.round(ageScore * 0.55 + leagueScore * 0.25 + capsScore * 0.2);
}

/** Tolerant read: missing file, truncated JSON (concurrent write from the
 *  precompute process), or a partial/malformed entry are all treated as "no
 *  prediction available" rather than a hard failure. */
function loadPredictionsTolerant(): PredictionsData {
  try {
    const raw = fs.readFileSync(PREDICTIONS_PATH, "utf-8");
    const parsed = JSON.parse(raw) as Partial<PredictionsData>;
    return {
      generatedAt: parsed.generatedAt ?? "",
      players: Array.isArray(parsed.players) ? parsed.players : [],
      teams: Array.isArray(parsed.teams) ? parsed.teams : [],
    };
  } catch {
    return { generatedAt: "", players: [], teams: [] };
  }
}

export interface MarketBaseEntry {
  slug: string;
  team: string;
  base: number; // 0..1
  prob: number; // 0..100
  source: "model" | "baseline";
}

export interface MarketBaseFile {
  generatedAt: string;
  entries: Record<string, MarketBaseEntry>; // key = "TEAM::slug"
}

function main() {
  const squads = JSON.parse(fs.readFileSync(SQUADS_PATH, "utf-8")) as SquadsData;
  const predictions = loadPredictionsTolerant();

  const byKey = new Map<string, (typeof predictions.players)[number]>();
  for (const pr of predictions.players) {
    if (!pr?.team || !pr?.name) continue; // tolerate partial entries
    byKey.set(`${pr.team.toUpperCase()}::${pr.name}`, pr);
  }

  const entries: Record<string, MarketBaseEntry> = {};
  let modelCount = 0;
  let baselineCount = 0;

  for (const team of squads.teams) {
    for (const player of team.players) {
      const slug = slugify(player.name);
      const pred = byKey.get(`${team.code.toUpperCase()}::${player.name}`);
      const hasValidPred = pred && Number.isFinite(pred.mean);
      const prob = hasValidPred ? pred!.mean : baselineProbability(player);
      const source: "model" | "baseline" = hasValidPred ? "model" : "baseline";
      if (source === "model") modelCount++;
      else baselineCount++;

      entries[`${team.code.toUpperCase()}::${slug}`] = {
        slug,
        team: team.code,
        base: Number((prob / 100).toFixed(4)),
        prob,
        source,
      };
    }
  }

  const out: MarketBaseFile = { generatedAt: new Date().toISOString(), entries };
  fs.writeFileSync(OUT_PATH, JSON.stringify(out, null, 2));
  console.log(
    `[reprice] wrote ${Object.keys(entries).length} entries to ${OUT_PATH} (model=${modelCount} baseline=${baselineCount})`,
  );
}

main();
